--- #YAML:1.0
name:                WSDL-Generator
version:             0.04
abstract:            Generates wsdl code without hassle
license:             ~
author:              
    - Pierre Denis <pdenis@fotango.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Hook:                   0.01
    Test::Simple:                  0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
